config/routes.rb
Rails.application.routes.draw do
  devise_for(:users,:controllers => { :registrations => 'user/registrations' })
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root(:to => 'wellcome#index')
  resources(:users, :only => [:show])
  resources(:friendships)
  
  get('my_portfolio',:to => 'users#my_portfolio')
  get('get_stock', :to => 'stocks#get_stock')
  
  post('user_stock', :to => 'user_stocks#create')
  delete('destroy_stock', :to => 'users#destroy_stock')
  get('my_friends', :to => 'users#my_friends')
  get('get_user' , :to => 'users#get_user')
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to(:user)
  belongs_to(:friend,:class_name => "User")
end

app/models/stock.rb
class Stock < ApplicationRecord
  
  has_many :user_stocks
  has_many :users , :through => :user_stocks
  def self.new_from_lookup(ticker_symbol)
    begin
    
      looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
      last_price = looked_up_stock.latest_price
      new(:ticker => looked_up_stock.symbol,:name => looked_up_stock.company_name,:last_price => last_price )
    rescue Exception => ex
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_stocks
  has_many :stocks , :through => :user_stocks
  has_many :friendships
  has_many :friends, :through => :friendships
  
  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action(:authenticate_user!)
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    friend_id = params[:id]
    friendship = Friendship.find_by_user_id_and_friend_id(current_user.id,friend_id)
    friendship.delete
    flash[:success] = "Friend Removed Successfully"
    redirect_to my_friends_path
  end
  
  def create
    friend_id = params[:friend_id]
    Friendship.create(:user_id => current_user.id, :friend_id => friend_id)
    redirect_to my_friends_path
  end
  
  
  
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def get_stock
    if params[:stock].blank?
      flash.now[:danger] = "You have typed an empty string"
    else
       @stock = Stock.new_from_lookup(params[:stock])
       flash.now[:danger] = "You have entered an incorrect symbol!!!" unless @stock
    end
    respond_to do |format|
          format.js { render :partial => 'users/result' }
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  
  
  private
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by_ticker(params[:stock_ticker])
    if stock.blank?
      stock =Stock.new_from_lookup(params[:stock_ticker])
      stock.save
    end
    
    stockCount = UserStock.where(:user_id => current_user.id).count
    
    if stockCount < 10
    
      check_stock_for_user = UserStock.find_by_user_id_and_stock_id(current_user.id,stock.id)
      if check_stock_for_user.present?
        flash[:danger] = "This ticker is already addded for current user"
      else
        @user_stocks = UserStock.new(:user => current_user, :stock => stock)
        @user_stocks.save
        flash[:success] = "#{params[:stock_ticker]} is successfully added to current user"
          
      end
    else
      flash[:danger] = "Cannot add more than 10 ticker for an user"
    end
    
    
    redirect_to my_portfolio_path
    
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @stock = Stock.new
    @user_stocks = Stock.select("id","name","ticker","last_price","user_id").joins(:user_stocks).where('user_stocks.user_id = ?',current_user.id)
  end
  
  def destroy_stock
    stock_id = params[:id]
    user_stock = UserStock.find_by_user_id_and_stock_id(current_user.id,stock_id)
    
    user_stock.delete
    flash[:success] = "Stock track removed successfully!!!"
    redirect_to my_portfolio_path
  end
  
  def my_friends
    @friends = current_user.friends
  end
  
  def get_user
    if params[:user_str].blank?
      flash.now[:danger] = "You have typed an empty string"
    else
      @users = User.where("(first_name like :user_str or last_name like :user_str or email like :user_str)", :user_str => "%#{params[:user_str]}%")
                    .where.not(:id => current_user.id)
      if @users.blank?
        flash.now[:danger] = "Could not find user!!!"  
      end
    end
    respond_to do |format|
      format.js { render :partial => 'users/friend_search' }
    end
  end
  
  def show
    user_id = params[:id]
    @user = User.find(user_id)
    @user_stocks = Stock.select("id","name","ticker","last_price","user_id").joins(:user_stocks).where('user_stocks.user_id = ?',user_id)
  end
  
  
end

app/controllers/wellcome_controller.rb
class WellcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tickerExists?(stock,user)
    dbStock = Stock.find_by_ticker(stock.ticker)
    
    if dbStock.blank?
      
      return false
      
    else
      check_stock_for_user = UserStock.find_by_user_id_and_stock_id(current_user.id,dbStock.id)
      return check_stock_for_user.present?
    end
  end
  
  def friend_Exists?(friend)
    friend = Friendship.find_by_user_id_and_friend_id(current_user.id,friend.id)
    return friend.present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

   

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon-apple.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">FinanceTracker</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "My Portfolio", my_portfolio_path  %></li>
              <li><%= link_to "Edit Information", edit_user_registration_path(current_user)  %></li>
              <li><%= link_to "My Friends", my_friends_path  %></li>
            <% end %>
          </ul>
          
          <ul class = "nav navbar-nav navbar-right">
            <% if user_signed_in? %>
               <li><i class = "fa fa-user fa-sm" style = "padding-top : 18px;">  <%= current_user.first_name%> </i></li>
              <li><%= link_to "logout",destroy_user_session_path, :method => :delete%></li>
             
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
   
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/_friend_search.html.erb
<div class = "results-block">
  <%= bootstrap_flash %>
</div>


  <table class = "table responsive ">
    <% @users.each do |user| %>
      <tr class = "info">
        <td>
          <%= user.full_name %>
        </td>
        <td>
          <strong> Email : </strong><%= user.email %>
        </td>
        <td>
          <%= link_to("Show Profile",user_path(user),:class => "btn btn-xs btn-info")%>
        </td>
        <td>
          <% if friend_Exists?(user) %>
            <div class = "label label-warning">This person is aleady added</div>
          <% else %>
            <%= link_to("Add Friend",friendships_path(:friend_id => user.id),:class => "btn btn-xs btn-success", :method => :post)%>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>

app/views/users/_friend_search.js.erb
$('#friend_search').html("<%= j (render 'users/friend_search.html') %>") 

app/views/users/_friends.html.erb
<h3>
  Friend List
</h3>
<hr>
<% if @friends.any? %>
  <table class = "table table-responsive table-striped">
    <thead>
      <td>Name</td>
      <td>Email</td>
      <td>Profile</td>
      <td>Remove</td>
    </thead>
    <tbody>
      <% @friends.each do |f|  %>
        <tr>
          <td>
            <%= "#{f.first_name} #{f.last_name}" %>
          </td>
          <td>
            <%= f.email %>
          </td>
          <td>
            <%= link_to("Show Profile",user_path(f),:class => "btn btn-xs btn-info")%>
          </td>
          <td><%= link_to("Remove Friend",friendship_path(f),:class => "btn btn-xs btn-danger",
                          :method => :delete, :data => {:confirm => "Are you sure?"})%></td>
        </tr>
      <% end %>
      
    </tbody>
  </table>
<% else %>
<div class = "alert alert-danger" align = "center">You Don't Have any Friends</div>
<% end %>

app/views/users/_result.html.erb
<div class = "results-block">
  <%= bootstrap_flash %>
</div>

<% if @stock && @stock.ticker %>
  <div class = "well results-block">
    <strong>symbol: </strong><%= @stock.ticker %>
    <strong>name: </strong><%= @stock.name %>
    <strong>latest price: </strong><%= @stock.last_price %>
    
    <% if !tickerExists?(@stock,current_user.id) %>
      <%= link_to("Add to Tracking list",user_stock_path(:stock_ticker => @stock.ticker),:method => :post, :class => "btn btn-xs btn-success") %>
    <% else %>
      <span class = "label label-primary"> This Stock is already added </span>
    <% end %>
    
  </div>
<% end %>

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html') %>") 

app/views/users/_user_stocks.html.erb
<% if @user_stocks.any? %>
  <table class = "table table-responsive table-striped">
    <thead>
      <td><strong>Ticker</strong></td>
      <td><strong>Name</strong></td>
      <td><strong>Last Price</strong></td>
      <% if @user_stocks.first.user_id == current_user.id %>
        <td><strong>Delete</strong></td>
      <% end %>
    </thead>
    <tbody>
      <% @user_stocks.each do |stock| %>
        <tr>
          <td><%= stock.ticker %></td>
          <td><%= stock.name %></td>
          <td><%= stock.last_price %></td>
          <% if stock.user_id == current_user.id %>
            <td><%= link_to "Remove" , destroy_stock_path(:id => stock.id),:method => :delete, :class => "btn btn-danger btn-xs", :data => {:confirm => "Are you sure?"} %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/my_friends.html.erb
<div align = "ceneter"><h2> My Friends</h2></div>
<hr>
<div>
  <%= form_tag(get_user_path,:method => :get, :remote => true) do %>
    <div class= "form-group row no-padding col-md-12">
      <div class = "col-md-10">
        <%= text_field_tag(:user_str ,params[:user_str],:autofocus => true,:placeholder => "Search User....", :class => "form-control input-lg") %>
      </div>
      <div class = "col-md-2">
        <%= button_tag(:type => :submit, :class => "btn btn-lg btn-success") do %>
          <i class = "fa fa-search"></i> Search For Friends
        <% end %>
      </div>
    </div>
  <% end %>
</div>


<div id = "friend_search" class = "row"></div>

<%= render 'friends' %>

  

app/views/users/my_portfolio.html.erb
<h1>Wellcome to My Portfolio</h1>

<h3>Search Stocks........</h3>
<div>
  <%= form_tag(get_stock_path,:method => :get, :remote => true) do %>
    <div class= "form-group row no-padding col-md-12">
      <div class = "col-md-10">
        <%= text_field_tag(:stock ,params[:stock],:autofocus => true,:placeholder => "Stock Ticker Symbol", :class => "form-control input-lg") %>
      </div>
      <div class = "col-md-2">
        <%= button_tag(:type => :submit, :class => "btn btn-lg btn-success") do %>
          <i class = "fa fa-search"></i> Lookup for Stock
        <% end %>
      </div>
    </div>
  <% end %>
</div>
  <br>
<div id = "results">
  
</div>

<div >
  <%= render 'user_stocks' %>
</div>

app/views/users/show.html.erb
<h2>User Profile </h2>
<hr>

<div class = "well">
  <p>
    <strong>user name :</strong> <%= @user.full_name %>
  </p>
  <p>
    <strong>email :</strong> <%= @user.email %>
  </p>
</div>

<%= render 'user_stocks' %>

app/views/wellcome/index.html.erb
<h1>Welcome to the finance tracker app</h1>
<%= link_to "logout",destroy_user_session_path, :method => :delete %>